GIT_TOP := $(shell git rev-parse --show-toplevel)

C_SRC_NAMES := logic
S_SRC_NAMES := logic
C_TEST_SRC_NAMES := logic

INCS := $(GIT_TOP)/make_c/test/misc_hdrs

include $(GIT_TOP)/colors.mk
include $(GIT_TOP)/make_c/module.mk
